const mongoose = require('mongoose');

const analyticsSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  reportType: {
    type: String,
    enum: ['weekly', 'monthly'],
    required: true
  },
  periodStartDate: {
    type: Date,
    required: true
  },
  periodEndDate: {
    type: Date,
    required: true
  },
  dominantEmotion: {
    type: String,
    required: true
  },
  emotionTrends: {
    type: Map,
    of: Number, // Example: { 'joy': 15, 'sadness': 3 }
    required: true
  },
  positiveToNegativeRatio: {
    type: Number, // Example: 2.5 (Positive / Negative)
    default: 1
  },
  aiSummary: {
    type: String, // Insight generated by Gemini
    required: true
  }
}, { timestamps: true });

module.exports = mongoose.model('Analytics', analyticsSchema);
